const sheetData=[{id:"1205175935",name:"Vaibhav Vashisth",age:20,weight:68,goal:"Muscular Body",bmi:23.5,category:"Normal Weight",ideal:65.9},{id:"1205172534",name:"Meenu Sharma",age:42,weight:67.6,goal:"Healthy Living",bmi:26.4,category:"Overweight",ideal:52.4},{id:"1205190731",name:"Hemant Sharma",age:51,weight:80,goal:"Weight Loss",bmi:27.7,category:"Overweight",ideal:65.9},{id:"1405100910",name:"User 1405",age:78,weight:85,goal:"Healthy Living",bmi:27.8,category:"Overweight",ideal:70.5},{id:"1205174000",name:"Alka Jha",age:34,weight:72,goal:"Weight Loss",bmi:28.1,category:"Overweight",ideal:58.0}];
let waterCount=0,currentUser=null,currentPlan=[];
let voices=[];let recognition=null;let isListening=false;
const TASK_BUCKETS=["daily","weekly","monthly"];

function userStoreKey(){return currentUser?`herbalife_user_${currentUser.id}`:null;}
function loadUserState(){const k=userStoreKey();if(!k)return null;return JSON.parse(localStorage.getItem(k)||"null")||{tasks:{},calendar:{},history:{}};}
function saveUserState(s){const k=userStoreKey();if(k)localStorage.setItem(k,JSON.stringify(s));}

function analyzeUser(){const input=document.getElementById('member-id-input').value.trim();const user=sheetData.find(u=>u.id===input);const errorBox=document.getElementById('error-box');const errorMsg=document.getElementById('error-msg');if(!user){errorMsg.innerText="Herbalife ID format invalid or not found. Check again.";errorBox.classList.remove('hidden');return;}errorBox.classList.add('hidden');document.getElementById('auth-section').classList.add('hidden');document.getElementById('hero-section').classList.add('hidden');document.getElementById('loading-ai').classList.remove('hidden');setTimeout(()=>{document.getElementById('loading-ai').classList.add('hidden');document.getElementById('dashboard').classList.remove('hidden');document.getElementById('status-dot').className="w-2 h-2 bg-green-500 rounded-full pulse-dot";document.getElementById('status-text').innerText="Online";currentUser=user;populateData(user);startAssistant();},1200);} 

function populateData(user){document.getElementById('user-name').innerText=user.name;document.getElementById('user-id-display').innerText=`Herbalife Official ID: ${user.id}`;document.getElementById('user-weight').innerText=`${user.weight} kg`;document.getElementById('user-bmi').innerText=user.bmi;document.getElementById('user-ideal').innerText=`${user.ideal} kg`;const bmiLabel=document.getElementById('bmi-label');bmiLabel.innerText=user.category;bmiLabel.className=`text-[10px] font-bold px-3 py-1 rounded-full uppercase tracking-tighter ${user.category==='Normal Weight'?'bg-green-500/20 text-green-400 border border-green-500/30':'bg-orange-500/20 text-orange-400 border border-orange-500/30'}`;
const feedback=user.category==="Overweight"?`नमस्ते ${user.name}! BMI ${user.bmi} है। आप 2-Way Shake Protocol और PPP फॉलो करें।`:`नमस्ते ${user.name}! आपका BMI normal range में है। Formula 1 shake और stamina routines जारी रखें।`;document.getElementById('ai-feedback').innerText=feedback;
const dietView=document.getElementById('view-diet');currentPlan=(user.category==="Overweight")?getWeightLossPlan():getHealthPlan();dietView.innerHTML=currentPlan.map(item=>`<div class="bg-white p-6 rounded-[2rem] border border-slate-100 card-shadow"><p class="text-xs font-bold text-slate-400">${item.time}</p><h4 class="text-sm font-bold text-slate-800">${item.title}</h4><p class="text-[11px] text-slate-500">${item.desc}</p></div>`).join('');
renderTasks('daily');renderCalendar();renderChart();speakFullReport();}

function getWeightLossPlan(){return[{time:"06:30 AM",title:"Detox Drink",desc:"Afresh + warm water"},{time:"08:30 AM",title:"Replacement Shake",desc:"F1 + PPP"},{time:"01:30 PM",title:"Indian Lunch",desc:"Roti, dal, sabzi"},{time:"05:00 PM",title:"Fitness Club Class",desc:"Join live class"},{time:"08:00 PM",title:"Dinner Protocol",desc:"F1 + PPP"}];}
function getHealthPlan(){return[{time:"06:30 AM",title:"Fitness Club Class",desc:"Join live class"},{time:"09:00 AM",title:"Nutrition Shake",desc:"F1 + fruit"},{time:"01:30 PM",title:"Full Indian Meal",desc:"Balanced meal"},{time:"05:00 PM",title:"Evening Online Class",desc:"Join live class"},{time:"08:30 PM",title:"Balanced Dinner",desc:"Light dinner"}];}

function showTab(tab){document.getElementById('view-diet').classList.add('hidden');document.getElementById('view-habits').classList.add('hidden');document.getElementById(`view-${tab}`).classList.remove('hidden');if(tab==='habits')renderCalendar();}
function addWater(){if(waterCount<4){waterCount+=0.25;document.getElementById('water-text').innerText=waterCount.toFixed(2);document.getElementById('water-progress-bar').style.width=`${(waterCount/4)*100}%`;}}

function buildTasks(bucket){const base={daily:["6:30 AM class join","5:00 PM class join","10 min yoga"],weekly:["Weekly weight check","Meal prep review"],monthly:["Coach review","Goal reset"]};return base[bucket].map((t,i)=>({id:`${bucket}_${i}`,title:t,time:bucket==='daily'?(i===0?'06:30':'17:00'):'Flexible'}));}
function renderTasks(bucket){const wrap=document.getElementById('routine-list');const state=loadUserState();const tasks=buildTasks(bucket);document.querySelectorAll('.task-btn').forEach(b=>b.classList.remove('tab-active'));document.getElementById(`btn-${bucket}`).classList.add('tab-active');wrap.innerHTML=tasks.map(t=>`<div class='p-3 rounded-xl border bg-slate-50'><div class='flex justify-between'><div><p class='text-sm font-semibold'>${t.title}</p><p class='text-[11px] text-slate-500'>Slot: ${t.time}</p></div><button onclick="verifyTask('${bucket}','${t.id}')" class='bg-slate-900 text-white px-3 py-1 rounded-lg text-xs'>Live Camera Verify (10s)</button></div><label class='text-xs mt-2 block'><input type='checkbox' ${(state.tasks[t.id])?'checked':''} onchange="toggleTask('${bucket}','${t.id}',this.checked)"> Mark done</label></div>`).join('');updateTaskProgress(bucket);}
function toggleTask(bucket,id,checked){const s=loadUserState();s.tasks[id]=checked;const today=new Date().toISOString().slice(0,10);if(!s.calendar[today])s.calendar[today]=[];if(checked&&!s.calendar[today].includes(id))s.calendar[today].push(id);saveUserState(s);updateTaskProgress(bucket);renderCalendar();renderChart();}
async function verifyTask(bucket,id){const v=document.getElementById('live-camera');try{const stream=await navigator.mediaDevices.getUserMedia({video:true,audio:false});v.srcObject=stream;v.classList.remove('hidden');speakText('कैमरा एनालिसिस शुरू. 10 सेकंड तक एक्टिव रहें।');setTimeout(()=>{stream.getTracks().forEach(t=>t.stop());v.classList.add('hidden');toggleTask(bucket,id,true);speakText('टास्क सत्यापित और पूरा मार्क कर दिया गया।');},10000);}catch(e){alert('Camera permission denied.');}}
function updateTaskProgress(bucket){const s=loadUserState();const tasks=buildTasks(bucket);const done=tasks.filter(t=>s.tasks[t.id]).length;const p=Math.round((done/tasks.length)*100);document.getElementById('task-progress-text').innerText=`${p}%`;document.getElementById('task-progress-bar').style.width=`${p}%`;const d=new Date().toISOString().slice(0,10);s.history[d]=p;saveUserState(s);} 
function renderCalendar(){const s=loadUserState();const el=document.getElementById('task-calendar');if(!el)return;const entries=Object.entries(s.calendar).slice(-7).reverse();el.innerHTML=entries.length?entries.map(([d,arr])=>`<div class='text-xs p-2 border rounded-lg'><b>${d}</b><br>${arr.join(', ')||'No tasks'}</div>`).join(''):'<p class="text-xs text-slate-500">No calendar activity yet</p>';}
function renderChart(){const s=loadUserState();const el=document.getElementById('progress-chart');const bars=Object.entries(s.history).slice(-7);el.innerHTML=bars.map(([d,p])=>`<div class='flex items-center gap-2 text-[10px]'><span class='w-24'>${d}</span><div class='h-2 bg-indigo-500 rounded' style='width:${p}%;min-width:4px'></div><span>${p}%</span></div>`).join('');}

function detectLang(text){return /[\u0900-\u097F\u0600-\u06FF]/.test(text)?'hi-IN':'en-US';}
function loadVoices(){voices=speechSynthesis.getVoices();}
function speakText(text){if(!window.speechSynthesis)return;const u=new SpeechSynthesisUtterance(text);u.lang=detectLang(text);const v=voices.find(x=>x.lang===u.lang)||voices.find(x=>x.lang.startsWith(u.lang.slice(0,2)));if(v)u.voice=v;speechSynthesis.cancel();speechSynthesis.speak(u);} 
function speakFullReport(){if(!currentUser)return;const txt=`${document.getElementById('ai-feedback').innerText} आपका आज का प्लान: ${currentPlan.map(x=>x.time+' '+x.title).join(', ')}`;speakText(txt);} 
function answerQuestion(q){if(!currentUser)return 'Please login first.';const l=q.toLowerCase();if(l.includes('bmi'))return `Aapka BMI ${currentUser.bmi} hai.`;if(l.includes('plan')||l.includes('task'))return `Aaj ke tasks: ${buildTasks('daily').map(t=>t.title).join(', ')}`;if(l.includes('weight'))return `Current weight ${currentUser.weight} kg hai.`;return `Aapka goal ${currentUser.goal} hai. 6:30 AM aur 5:00 PM class join karein.`;}
function startAssistant(){loadVoices();if(!('webkitSpeechRecognition'in window||'SpeechRecognition'in window))return;const SR=window.SpeechRecognition||window.webkitSpeechRecognition;recognition=new SR();recognition.continuous=true;recognition.interimResults=false;recognition.lang='hi-IN';recognition.onresult=(e)=>{const text=e.results[e.results.length-1][0].transcript.trim();document.getElementById('assistant-log').innerText=`You: ${text}`;speakText(answerQuestion(text));};recognition.onend=()=>{if(isListening)recognition.start();};isListening=true;recognition.start();}
function toggleAssistant(){if(!recognition)return;isListening=!isListening;document.getElementById('assistant-toggle').innerText=isListening?'Pause Assistant':'Resume Assistant';if(!isListening){recognition.stop();speechSynthesis.cancel();}else recognition.start();}
function resetApp(){location.reload();}
speechSynthesis.onvoiceschanged=loadVoices;
