function detectLang(text){return /[\u0900-\u097F\u0600-\u06FF]/.test(text)?'hi-IN':'en-US';}
function loadVoices(){if(!window.speechSynthesis)return;appState.voices=speechSynthesis.getVoices();}
function saveConversation(role,text){if(!appState.currentUser)return;const s=loadUserState();s.conversation.push({role,text,ts:Date.now()});s.conversation=s.conversation.slice(-40);saveUserState(s);} 
function speakText(text,onEnd){if(!window.speechSynthesis||!text)return;const u=new SpeechSynthesisUtterance(text);u.lang=detectLang(text);u.pitch=1.1;u.rate=1;const female=appState.voices.find(x=>x.lang.startsWith(u.lang.slice(0,2))&&/female|zira|susan|google हिंदी|heera/i.test(x.name));u.voice=female||appState.voices.find(x=>x.lang.startsWith(u.lang.slice(0,2)));appState.lastSpeechText=text;u.onend=()=>{if(onEnd)onEnd();};speechSynthesis.cancel();speechSynthesis.speak(u);saveConversation('assistant',text);} 
function speakFullReport(){if(!appState.currentUser)return;const txt=`${document.getElementById('ai-feedback').innerText} आपका आज का प्लान: ${appState.currentPlan.map(x=>x.time+' '+x.title).join(', ')}`;speakText(txt);} 
async function answerQuestion(q){if(!appState.currentUser)return 'Please login first.';const l=q.toLowerCase();if(l.includes('bmi'))return `Aapka BMI ${appState.currentUser.bmi} hai.`;if(l.includes('plan')||l.includes('task'))return `Aaj ke tasks: ${buildTasks('daily').map(t=>t.title).join(', ')}`;if(l.includes('weight'))return `Current weight ${appState.currentUser.weight} kg hai.`;
  const fallback=`Aapka goal ${appState.currentUser.goal} hai. 6:30 AM aur 5:00 PM class join karein.`;
  try{const controller=new AbortController();const t=setTimeout(()=>controller.abort(),2500);const resp=await fetch(`https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(q.split(' ').slice(0,4).join(' '))}`,{signal:controller.signal});clearTimeout(t);if(resp.ok){const data=await resp.json();if(data.extract)return data.extract.slice(0,220);}return fallback;}catch(e){return fallback;}
}
function setAssistantLog(msg){const el=document.getElementById('assistant-log');if(el)el.innerText=msg;}
function startAssistant(){loadVoices();if(!('webkitSpeechRecognition'in window||'SpeechRecognition'in window)){setAssistantLog('Voice recognition not supported in this browser.');return;}const SR=window.SpeechRecognition||window.webkitSpeechRecognition;appState.recognition=new SR();appState.recognition.continuous=true;appState.recognition.interimResults=false;appState.recognition.lang='hi-IN';appState.recognition.onresult=async (e)=>{if(appState.awaitingUserTurn!==true)return;const text=e.results[e.results.length-1][0].transcript.trim();setAssistantLog(`You: ${text}`);saveConversation('user',text);appState.awaitingUserTurn=false;const ans=await answerQuestion(text);speakText(ans,()=>setTimeout(beginAssistantTurn,120));};appState.recognition.onend=()=>{if(appState.isListening)appState.recognition.start();};appState.isListening=true;appState.awaitingUserTurn=false;appState.recognition.start();beginAssistantTurn();}
function beginAssistantTurn(){if(!appState.currentUser)return;const greet=`Hi ${appState.currentUser.name}, hello! Main aapki AI wellness assistant hoon. Aap apna sawal boliye.`;setAssistantLog('AI: Greeting and asking your question...');speakText(greet,()=>{appState.awaitingUserTurn=true;setAssistantLog('AI: I am listening. Tap Speak to AI and ask now.');});}
function startUserSpeakTurn(){if(!appState.recognition)return;appState.awaitingUserTurn=true;setAssistantLog('AI: Listening to your question... बोलिए।');}
function toggleAssistantListening(){if(!appState.recognition)return;appState.isListening=!appState.isListening;const navBtn=document.getElementById('assistant-toggle');if(navBtn)navBtn.innerText=appState.isListening?'Mute Mic':'Unmute Mic';if(!appState.isListening){appState.recognition.stop();setAssistantLog('Mic muted. AI speech continues.');}else{appState.recognition.start();setAssistantLog('Mic unmuted.');}}
function stopAssistantSpeaking(){if(window.speechSynthesis){speechSynthesis.cancel();setAssistantLog('AI voice stopped.');}}
function speakSavedConversation(){const s=loadUserState();const last=s.conversation[s.conversation.length-1];if(last)speakText(`पिछली बात यह थी: ${last.text}`);} 
if(window.speechSynthesis){speechSynthesis.onvoiceschanged=loadVoices;}
