function detectLang(text){return /[\u0900-\u097F\u0600-\u06FF]/.test(text)?'hi-IN':'en-US';}
function loadVoices(){if(!window.speechSynthesis)return;appState.voices=speechSynthesis.getVoices();}
function saveConversation(role,text){if(!appState.currentUser)return;const s=loadUserState();s.conversation.push({role,text,ts:Date.now()});s.conversation=s.conversation.slice(-30);saveUserState(s);} 
function speakText(text){if(!window.speechSynthesis||!text)return;const u=new SpeechSynthesisUtterance(text);u.lang=detectLang(text);u.pitch=1.1;u.rate=1;const female=appState.voices.find(x=>x.lang.startsWith(u.lang.slice(0,2))&&/female|zira|susan|google हिंदी|heera/i.test(x.name));u.voice=female||appState.voices.find(x=>x.lang.startsWith(u.lang.slice(0,2)));appState.lastSpeechText=text;appState.lastUtterance=u;speechSynthesis.cancel();speechSynthesis.speak(u);saveConversation('assistant',text);} 
function speakFullReport(){if(!appState.currentUser)return;const txt=`${document.getElementById('ai-feedback').innerText} आपका आज का प्लान: ${appState.currentPlan.map(x=>x.time+' '+x.title).join(', ')}`;speakText(txt);} 
function answerQuestion(q){if(!appState.currentUser)return 'Please login first.';const l=q.toLowerCase();if(l.includes('bmi'))return `Aapka BMI ${appState.currentUser.bmi} hai.`;if(l.includes('plan')||l.includes('task'))return `Aaj ke tasks: ${buildTasks('daily').map(t=>t.title).join(', ')}`;if(l.includes('weight'))return `Current weight ${appState.currentUser.weight} kg hai.`;if(l.includes('search'))return 'मैं direct web search APIs बिना key के integrate नहीं कर सकती, लेकिन आपकी profile के अनुसार best जवाब दे रही हूँ।';return `Aapka goal ${appState.currentUser.goal} hai. 6:30 AM aur 5:00 PM class join karein.`;}
function startAssistant(){loadVoices();if(!('webkitSpeechRecognition'in window||'SpeechRecognition'in window)){document.getElementById('assistant-log').innerText='Voice recognition not supported in this browser.';return;}const SR=window.SpeechRecognition||window.webkitSpeechRecognition;appState.recognition=new SR();appState.recognition.continuous=true;appState.recognition.interimResults=false;appState.recognition.lang='hi-IN';appState.recognition.onresult=(e)=>{const text=e.results[e.results.length-1][0].transcript.trim();document.getElementById('assistant-log').innerText=`You: ${text}`;saveConversation('user',text);speakText(answerQuestion(text));};appState.recognition.onend=()=>{if(appState.isListening)appState.recognition.start();};appState.isListening=true;appState.recognition.start();}
function toggleAssistantListening(){if(!appState.recognition)return;appState.isListening=!appState.isListening;document.getElementById('assistant-toggle').innerText=appState.isListening?'Pause Listening':'Resume Listening';if(!appState.isListening)appState.recognition.stop();else appState.recognition.start();}
function stopAssistantSpeaking(){if(window.speechSynthesis)speechSynthesis.cancel();}
function resumeAssistantSpeaking(){if(appState.lastSpeechText)speakText(`क्या मैं पिछली बात जारी रखूं? ${appState.lastSpeechText}`);} 
function speakSavedConversation(){const s=loadUserState();const last=s.conversation[s.conversation.length-1];if(last)speakText(`पिछली बात यह थी: ${last.text}`);} 
if(window.speechSynthesis){speechSynthesis.onvoiceschanged=loadVoices;}
